package com.blogspot.androidgaidamak.acustomgooglesearchclient.provider.favourite;

import com.blogspot.androidgaidamak.acustomgooglesearchclient.provider.base.BaseModel;

import java.util.Date;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/**
 * Image entity from google search which was aded to favourites.
 */
public interface FavouriteModel extends BaseModel {

    /**
     * Link to thumbnail image (generated by google).
     * Cannot be {@code null}.
     */
    @NonNull
    String getThumbnailLink();

    /**
     * Link to real image (the big one).
     * Cannot be {@code null}.
     */
    @NonNull
    String getDisplayLink();

    /**
     * Get the {@code title} value.
     * Cannot be {@code null}.
     */
    @NonNull
    String getTitle();
}
