package com.blogspot.androidgaidamak.acustomgooglesearchclient.provider.favourite;

import android.net.Uri;
import android.provider.BaseColumns;

import com.blogspot.androidgaidamak.acustomgooglesearchclient.provider.FavouritesProvider;
import com.blogspot.androidgaidamak.acustomgooglesearchclient.provider.favourite.FavouriteColumns;

/**
 * Image entity from google search which was aded to favourites.
 */
public class FavouriteColumns implements BaseColumns {
    public static final String TABLE_NAME = "favourite";
    public static final Uri CONTENT_URI = Uri.parse(FavouritesProvider.CONTENT_URI_BASE + "/" + TABLE_NAME);

    /**
     * Primary key.
     */
    public static final String _ID = BaseColumns._ID;

    /**
     * Link to thumbnail image (generated by google).
     */
    public static final String THUMBNAIL_LINK = "thumbnail_link";

    /**
     * Link to real image (the big one).
     */
    public static final String DISPLAY_LINK = "display_link";

    public static final String TITLE = "title";


    public static final String DEFAULT_ORDER = TABLE_NAME + "." +_ID;

    // @formatter:off
    public static final String[] ALL_COLUMNS = new String[] {
            _ID,
            THUMBNAIL_LINK,
            DISPLAY_LINK,
            TITLE
    };
    // @formatter:on

    public static boolean hasColumns(String[] projection) {
        if (projection == null) return true;
        for (String c : projection) {
            if (c == THUMBNAIL_LINK || c.contains("." + THUMBNAIL_LINK)) return true;
            if (c == DISPLAY_LINK || c.contains("." + DISPLAY_LINK)) return true;
            if (c == TITLE || c.contains("." + TITLE)) return true;
        }
        return false;
    }

}
